---
title: "Figure 3: Weight Interpretation and Gene Set Enrichment Analysis"
author: "Yichen Zhang"
output:
  html_document:
    self_contained: true
    keep_md: true
---
```{r setup, echo=FALSE, message=FALSE}
source("util.R")
source("util_analysis.R")
library(ggplot2)
library(data.table)
library(magrittr)
library(reshape2)
library(dplyr)
library(patchwork)
library(RColorBrewer)
library(grDevices)
library(msigdbr)
library(goseq)
library(fgsea)
library(dplyr)
library(tidyr)
library(rsvd)
library(R.utils)
knitr::opts_chunk$set(results = "asis")
```

```{r readpath, echo=FALSE}
Save_Path <- "models/DeltaTopic"
```

```{r read genes, echo=FALSE}
## Read genes and marker genes from Peng et al 2019
.genes <- fread(paste0(Save_Path, "/var_names.csv.gz"), header = F)
setnames(.genes, "V1", "gene")
# Cell type marker genes from Peng et al 2019
.db = readxl::read_xls("data/cell_type_markers/cell_markers_Peng2019.xls")
setnames(.db, "Gene", "gene")
setnames(.db, "Cell type", "cell type")
.db <- as.data.table(.db)
```

```{r get full weights, echo=FALSE}
## Compute the weights (rho and delta) from spike and slab parameters
readDT_melt <- function(Save_Path, parameter, target){
    readpath <- paste0(Save_Path, "/model_parameters/", paste0(parameter, "_", target, ".txt"))
    a <- fread(readpath, col.names = .genes$gene)
    a[, Var1 := rownames(a)] %>% reshape2::melt(id.vars = "Var1", value.name = parameter)
}

target <- "rho"
file <- paste0(Save_Path, "/dt_rho.rds")
if(!file.exists(file)){
    param.dt.rho <- readDT_melt(Save_Path, "slab_mean", target) %>%
        merge(readDT_melt(Save_Path, "slab_lnvar", target), allow.cartesian = TRUE) %>%
        merge(readDT_melt(Save_Path, "spike_logit", target), allow.cartesian = TRUE) %>%
        merge(.genes, by.x = "variable", by.y = "gene", allow.cartesian = TRUE) %>%
        mutate(pip = 1/(1 + exp(-spike_logit))) %>%
        mutate(row = `Var1`, col = `variable`, weight = slab_mean * pip) %>%
        mutate(parameter := target)
    saveRDS(param.dt.rho, file)
}
param.dt.rho <- readRDS(file)

target <- "delta"
file <- paste0(Save_Path, "/dt_delta.rds")
if(!file.exists(file)){
    param.dt.delta <- readDT_melt(Save_Path, "slab_mean", target) %>%
        merge(readDT_melt(Save_Path, "slab_lnvar", target), allow.cartesian = TRUE) %>%
        merge(readDT_melt(Save_Path, "spike_logit", target), allow.cartesian = TRUE) %>%
        merge(.genes, by.x = "variable", by.y = "gene", allow.cartesian = TRUE) %>%
        mutate(pip = 1/(1 + exp(-spike_logit))) %>%
        mutate(row = `Var1`, col = `variable`, weight = slab_mean * pip) %>%
        mutate(parameter := target)

    saveRDS(param.dt.delta, file)
}
param.dt.delta <- readRDS(file)
```

## Rho topics correspond to known cell types
```{r fig.width=9, fig.height=5, echo=FALSE}
cutoff_rho <- 4

plt <- celltype_heatmap(param.dt.rho, .db[`p value` <=0, tail(.SD, 70) ,by = `cell type`], cutoff_rho)
print(plt)
.ggsave(paste0(Save_Path,"/figures/sparse_marker_genes_rho.pdf"), plot=plt,
        width=9, height=10)   
```

## Rho topics weights on all genes
```{r heatmap rho weights all genes, fig.width=9, fig.height=5, echo=FALSE}
cutoff_rho <- 10

.show.param.allgenes.rho <-
    param.dt.rho %>%
    mutate(weight = pmin(pmax(weight, -cutoff_rho), cutoff_rho)) %>%
    order.pair(ret.tab = TRUE) %>%
    as.data.table

topgenes <- param.dt.rho %>%   # Top N highest values by group
  arrange(desc(weight)) %>%
  group_by(row) %>%
  slice(1:3)

topgenes_match <- aggregate(topgenes$variable, by = list(topgenes$Var1), FUN = paste0, collapse = "/")

p <-
    ggplot(.show.param.allgenes.rho, aes(col, row, fill = weight)) +
    theme(legend.position = "top") +
    geom_tile() + xlab("genes") + ylab("topics") +
    scale_fill_distiller("topic-specific\ngene activities", palette = "RdBu", direction=-1) +
    scale_y_discrete(breaks = topgenes_match$Group.1, labels = paste0(topgenes_match$Group.1, ", ", topgenes_match$x))
    
print(p)
.ggsave(paste0(Save_Path,"/figures/sparse_heatmap_genes_rho.pdf"), plot=p,
        width=9, height=5)
```

## Delta topic weights on all genes

```{r heatmap delta weights allgenes, fig.width=9, fig.height=5, echo=FALSE}
cutoff_delta <- 10
.show.param.allgenes.delta <-
    param.dt.delta %>%
    mutate(weight = pmin(pmax(weight, -cutoff_delta), cutoff_delta)) %>%
    order.pair(ret.tab = TRUE) %>%
    as.data.table

topgenes <- param.dt.delta %>%   # Top N highest values by group
  arrange(desc(weight)) %>%
  group_by(row) %>%
  slice(1:3)

topgenes_match <- aggregate(topgenes$variable, by = list(topgenes$Var1), FUN = paste0, collapse = "/")

p <-
    ggplot(.show.param.allgenes.delta, aes(col, row, fill = weight)) +
    theme(legend.position = "top") +
    geom_tile() + xlab("genes") + ylab("topics") +
    scale_y_discrete(breaks = topgenes_match$Group.1, labels = paste0(topgenes_match$Group.1, ", ", topgenes_match$x)) +
    scale_fill_distiller("topic-specific\ngene activities", palette = "RdBu", direction=-1)

print(p)

.ggsave(paste0(Save_Path,"/figures/sparse_heatmap_genes_delta.pdf"), plot=p,
        width=9, height=5)
```

## Gene Set Enrichment Analysis (GSEA)

```{r gse setup, echo=FALSE}
# Load msigdb genesets
IMMUNESIG.human.db <- msigdbr::msigdbr(species = "human",
										category = "C7",
										subcategory = "IMMUNESIGDB")

IMMUNESIG.lol <- IMMUNESIG.human.db %>% select(gene_symbol, gs_name) %>% make.gs.lol()

HALLMARK.human.db <- msigdbr::msigdbr(species = "human",
										category = "H")

HALLMARK.lol <- HALLMARK.human.db %>% select(gene_symbol, gs_name) %>% make.gs.lol()

KEGG.human.db <- msigdbr::msigdbr(species = "human",
										category = "C2",
                                        subcategory = "CP")

KEGG.lol <- KEGG.human.db %>% select(gene_symbol, gs_name) %>% make.gs.lol()

.show.param.full.delta <-
    param.dt.delta %>%
    mutate(pip = 1/(1 + exp(-spike_logit))) %>% 
    mutate(row = `Var1`, col = `variable`, weight = slab_mean * pip) %>%
    order.pair(ret.tab = TRUE) %>%
    as.data.table

.show.param.full.rho <-
    param.dt.rho %>%
    mutate(pip = 1/(1 + exp(-spike_logit))) %>% 
    mutate(row = `Var1`, col = `variable`, weight = slab_mean * pip) %>%
    order.pair(ret.tab = TRUE) %>%
    as.data.table
```

### immunesig_delta

```{r fgsea.alltopic.immunesig_delta, fig.width=9, fig.height=5, echo = FALSE}

dir.create(paste0(Save_Path, "/gsea"), showWarnings = FALSE)
file <- paste0(Save_Path, "/gsea/IMMUNESIG_delta.rds")
if(!file.exists(file)){
    result_IMMUNESIG_delta <- fgsea_all_topics(.show.param.full.delta, IMMUNESIG.lol)
    saveRDS(result_IMMUNESIG_delta, file)
}
result_IMMUNESIG_delta <- readRDS(file)
present.fgsea.result.alltopics(result_IMMUNESIG_delta, N_pathways = 1, N_genes = 3) -> fgsea_result
fgsea_result %>% knitr::kable()
# topics with significant enrichment with cutoff at 0.1
p_cutoff <- 0.1
topics_with_sig_enrichment <- fgsea_result$topic[fgsea_result$padj < p_cutoff]
# only showing the significant pathways
.db_IMMUNESIG = get_geneset.dt(result_IMMUNESIG_delta, N_genes = 10, p_cutoff = p_cutoff)

# omit the GSE in pathway names in the plotting
.db_IMMUNESIG_to_plot <- .db_IMMUNESIG
.db_IMMUNESIG_to_plot$pathway <- gsub("^.*?_","",.db_IMMUNESIG_to_plot$pathway)
plt <- geneset_heatmap(param.dt.delta[row %in% topics_with_sig_enrichment], .db_IMMUNESIG_to_plot, weight_cutoff = 3)
print(plt)

.ggsave(paste0(Save_Path,"/figures/heatmap_delta_immunesig.pdf"), plot=plt,
        width=9, height=5)
```

### Hallmark_delta

```{r fgsea.alltopic.hallmark_delta, fig.width=9, fig.height=5, echo = FALSE}
file <- paste0(Save_Path, "/gsea/HALLMARK_delta.rds")
if(!file.exists(file)){
    result_HALLMARK <- fgsea_all_topics(.show.param.full.delta, HALLMARK.lol)
    saveRDS(result_HALLMARK, file)
}
result_HALLMARK <- readRDS(file)
present.fgsea.result.alltopics(result_HALLMARK, N_pathways = 1, N_genes = 3) -> fgsea_result
fgsea_result %>% knitr::kable()

# topics with significant enrichment with cutoff at 0.05
p_cutoff <- 0.05
topics_with_sig_enrichment <- fgsea_result$topic[fgsea_result$padj < p_cutoff]
# only showing the significant pathways

.db_HALLMARK = get_geneset.dt(result_HALLMARK, N_genes = 10, p_cutoff = p_cutoff)

# omit the GSE in pathway names in the plotting
.db_HALLMARK_to_plot <- .db_HALLMARK
.db_HALLMARK_to_plot$pathway <- gsub("^.*?_","",.db_HALLMARK_to_plot$pathway)

plt <- geneset_heatmap(param.dt.delta[row %in% topics_with_sig_enrichment], .db_HALLMARK_to_plot, 3)
print(plt)

.ggsave(paste0(Save_Path,"/figures/heatmap_delta_hallmark.pdf"), plot=plt,
        width=9, height=5)
```

#### KEGG_delta

```{r fgsea.alltopics.kegg_delta, fig.width=9, fig.height=5, echo = FALSE}
file <- paste0(Save_Path, "/gsea/KEGG_delta.rds")
if(!file.exists(file)){
    result_KEGG <- fgsea_all_topics(.show.param.full.delta, KEGG.lol)
    saveRDS(result_KEGG, file)
}
result_KEGG <- readRDS(file)

present.fgsea.result.alltopics(result_KEGG, N_pathways = 1, N_genes = 3) -> fgsea_result
fgsea_result %>% knitr::kable()

# topics with significant enrichment with cutoff at 0.1
p_cutoff <- 0.1
topics_with_sig_enrichment <- fgsea_result$topic[fgsea_result$padj < p_cutoff]
# only showing the significant pathways

.db_KEGG = get_geneset.dt(result_KEGG, N_genes = 10, p_cutoff = p_cutoff)

# omit the GSE in pathway names in the plotting
.db_KEGG_to_plot <- .db_KEGG

plt <- geneset_heatmap(param.dt.delta[row %in% topics_with_sig_enrichment], .db_KEGG_to_plot, 2.5)
print(plt)

.ggsave(paste0(Save_Path,"/figures/heatmap_delta_kegg.pdf"), plot=plt,
        width=9, height=5)
```

### aggregate all gsea(delta)
```{r aggregate.gsea_delta, echo=FALSE}
fgsea.results.aggregata <- tibble()

fgsea.results.aggregata <- bind_rows(fgsea.results.aggregata,present.fgsea.result.alltopics(result_KEGG, N_pathways = 1, N_genes = 3))
fgsea.results.aggregata <- bind_rows(fgsea.results.aggregata,present.fgsea.result.alltopics(result_HALLMARK, N_pathways = 1, N_genes = 3))
fgsea.results.aggregata <- bind_rows(fgsea.results.aggregata,present.fgsea.result.alltopics(result_IMMUNESIG_delta, N_pathways = 1, N_genes = 3))

fgsea.results.aggregata <- fgsea.results.aggregata %>% as.data.table
fgsea.results.aggregata[,.SD[which.min(padj)], by = topic] %>% select(topic,pathway,padj, topGenes) %>% knitr::kable()
```

### immunesig_rho

```{r fgsea.alltopic.immunesig_rho, fig.width=9, fig.height=5, echo = FALSE}
file <- paste0(Save_Path, "/gsea/IMMUNESIG_rho.rds")
if(!file.exists(file)){
    result_IMMUNESIG_rho <- fgsea_all_topics(.show.param.full.rho, IMMUNESIG.lol)
    saveRDS(result_IMMUNESIG_rho, file)
}
result_IMMUNESIG_rho <- readRDS(file)
present.fgsea.result.alltopics(result_IMMUNESIG_rho, N_pathways = 1, N_genes = 3) %>% knitr::kable()

.db_IMMUNESIG = get_geneset.dt(result_IMMUNESIG_rho, N_genes = 10, p_cutoff = 0.1)
plt <- geneset_heatmap(param.dt.rho, .db_IMMUNESIG, cutoff_rho)
print(plt)

.ggsave(paste0(Save_Path,"/figures/heatmap_rho_immunesig.pdf"), plot=plt,
        width=9, height=5)
```

### Hallmark_rho

```{r fgsea.alltopic.hallmark_rho, fig.width=9, fig.height=5, echo = FALSE}
file <- paste0(Save_Path, "/gsea/HALLMARK_rho.rds")
if(!file.exists(file)){
    result_HALLMARK <- fgsea_all_topics(.show.param.full.rho, HALLMARK.lol)
    saveRDS(result_HALLMARK, file)
}
result_HALLMARK <- readRDS(file)
present.fgsea.result.alltopics(result_HALLMARK, N_pathways = 1, N_genes = 3) %>% knitr::kable()

.db_HALLMARK = get_geneset.dt(result_HALLMARK, N_genes = 10, p_cutoff = 0.1)
plt <- geneset_heatmap(param.dt.rho, .db_HALLMARK, cutoff_rho)
print(plt)

.ggsave(paste0(Save_Path,"/figures/heatmap_rho_hallmark.pdf"), plot=plt,
        width=9, height=5)
```

### KEGG_rho

```{r fgsea.alltopics.kegg_rho, fig.width=9, fig.height=5, echo = FALSE}
file <- paste0(Save_Path, "/gsea/KEGG_rho.rds")
if(!file.exists(file)){
    result_KEGG <- fgsea_all_topics(.show.param.full.rho, KEGG.lol)
    saveRDS(result_KEGG, file)
}
result_KEGG <- readRDS(file)

present.fgsea.result.alltopics(result_KEGG, N_pathways = 1, N_genes = 3) %>% knitr::kable()

.db_KEGG = get_geneset.dt(result_KEGG, N_genes = 10, p_cutoff = 0.1)
plt <- geneset_heatmap(param.dt.rho, .db_KEGG, cutoff_rho)
print(plt)

.ggsave(paste0(Save_Path,"/figures/heatmap_rho_kegg.pdf"), plot=plt,
        width=9, height=5)
```

### Topic frequency

#### topic_freq_rho_cell
```{r fretable bar plot, warning=FALSE, echo= FALSE}
topics <- fread(paste0(Save_Path, "/topics.csv")) # python 0-based indexing
topics <- topics[, -1]
k <- apply(t(topics), 2, which.max)
freq_table <- data.table(k %>% table())
colnames(freq_table)  <- c("topic", "freq")
# manually fill in for the empty topics
empty_topics <- data.table(topic = c("13","16","20","29"), freq = c(1,1,1,1))
freq_table <- rbind(freq_table, empty_topics)

# rho cell types
topic_order <- as.character(c(8,10,15,18,25,28,20,21,24,16,13,31,29,5,23,12,32,4,11,2,7,3,22,19,17,14,9,27,30,1,26,6))

p <- ggplot(freq_table, aes(y = log10(freq), x = topic)) +
        geom_bar(stat="identity") +
        theme_bw()+
        xlab("Topic") + ylab("Frequency (Log10)") +
        scale_x_discrete(limits = rev(topic_order)) +
        coord_flip()
p
.ggsave(paste0(Save_Path,"/figures/topic_freq_rho_cell.pdf"), plot=p,
        width=5, height=9)

```

#### topic_freq_delta_immune
```{r, echo=F}

topic_order <- as.character(c(23,17,20,28,8,2,4,30,24))

p <- ggplot(freq_table, aes(y = log10(freq), x = topic)) +
        geom_bar(stat="identity") +
        xlab("Topic") + ylab("Frequency (Log10)") +
        theme_bw() +
        scale_x_discrete(limits = rev(topic_order)) +
        coord_flip()
p
.ggsave(paste0(Save_Path,"/figures/topic_freq_delta_immune.pdf"), plot=p,
        width=5, height=5)

```

#### topic_freq_delta_KEGG
```{r, echo=F}
# gsea KEGG db

topic_order <- as.character(c(29,31,9,17,4,18))

p <- ggplot(freq_table, aes(y = log10(freq), x = topic)) +
        geom_bar(stat="identity") +
        xlab("Topic") + ylab("Frequency (Log10)") +
        theme_bw() +
        scale_x_discrete(limits = rev(topic_order)) +
        coord_flip()
p
.ggsave(paste0(Save_Path,"/figures/topic_freq_delta_KEGG.pdf"), plot=p,
        width=5, height=5)

```

#### topic_freq_delta_HALLMARK
```{r, echo=F}
# gsea HALLMARK db

topic_order <- as.character(c(3,17,19,5,14,26,6,18,15,24,16,12,8,28))

p <- ggplot(freq_table, aes(y = log10(freq), x = topic)) +
        geom_bar(stat="identity") +
        xlab("Topic") + ylab("Frequency (Log10)") +
        theme_bw() +
        scale_x_discrete(limits = rev(topic_order)) +
        coord_flip()
p
.ggsave(paste0(Save_Path,"/figures/topic_freq_delta_HALLMARK.pdf"), plot=p,
        width=5, height=5)
```
