---
title: "Figure 4 Vector fields and cell type annotation"
author: "Yichen Zhang"
output:
  html_document:
    self_contained: true
    keep_md: true
---
```{r setup, echo=FALSE, message=FALSE}
source("util.R")
source("util_analysis.R")
library(ggplot2)
library(data.table)
library(magrittr)
library(reshape2)
library(dplyr)
library(ggrepel)
library(patchwork)
library(RColorBrewer)
library(grDevices)
library(msigdbr)
library(goseq)
library(fgsea)
library(dplyr)
library(tidyr)
library(rsvd)
library(R.utils)
knitr::opts_chunk$set(results = "asis")
```

```{r readpath, echo=FALSE}
Save_Path <- "models/DeltaTopic"
```

```{r read genes, echo=FALSE}
## Read genes and marker genes from Peng et al 2019
.genes <- fread(paste0(Save_Path, "/var_names.csv.gz"), header = F)
setnames(.genes, "V1", "gene")
# Cell type marker genes from Peng et al 2019
.db = readxl::read_xls("data/cell_type_markers/cell_markers_Peng2019.xls")
setnames(.db, "Gene", "gene")
setnames(.db, "Cell type", "cell type")
.db <- as.data.table(.db)
```

```{r get full weights, echo=FALSE}
## Compute the weights (rho and delta) from spike and slab parameters
readDT_melt <- function(Save_Path, parameter, target){
    readpath <- paste0(Save_Path, "/model_parameters/", paste0(parameter, "_", target, ".txt"))
    a <- fread(readpath, col.names = .genes$gene)
    a[, Var1 := rownames(a)] %>% reshape2::melt(id.vars = "Var1", value.name = parameter)
}

target <- "rho"
file <- paste0(Save_Path, "/dt_rho.rds")
if(!file.exists(file)){
    param.dt.rho <- readDT_melt(Save_Path, "slab_mean", target) %>%
        merge(readDT_melt(Save_Path, "slab_lnvar", target), allow.cartesian = TRUE) %>%
        merge(readDT_melt(Save_Path, "spike_logit", target), allow.cartesian = TRUE) %>%
        merge(.genes, by.x = "variable", by.y = "gene", allow.cartesian = TRUE) %>%
        mutate(pip = 1/(1 + exp(-spike_logit))) %>%
        mutate(row = `Var1`, col = `variable`, weight = slab_mean * pip) %>%
        mutate(parameter := target)
    saveRDS(param.dt.rho, file)
}
param.dt.rho <- readRDS(file)

target <- "delta"
file <- paste0(Save_Path, "/dt_delta.rds")
if(!file.exists(file)){
    param.dt.delta <- readDT_melt(Save_Path, "slab_mean", target) %>%
        merge(readDT_melt(Save_Path, "slab_lnvar", target), allow.cartesian = TRUE) %>%
        merge(readDT_melt(Save_Path, "spike_logit", target), allow.cartesian = TRUE) %>%
        merge(.genes, by.x = "variable", by.y = "gene", allow.cartesian = TRUE) %>%
        mutate(pip = 1/(1 + exp(-spike_logit))) %>%
        mutate(row = `Var1`, col = `variable`, weight = slab_mean * pip) %>%
        mutate(parameter := target)

    saveRDS(param.dt.delta, file)
}
param.dt.delta <- readRDS(file)
```

### 2D - vector fields
```{r 2D vector filds, fig.width=9, fig.height=5, echo=FALSE}
set.seed(666) # for rsvd reproducibility

# convert weight.dt to matrix
## rho weight

dcast(param.dt.rho, row  ~ col, value.var = "weight") -> weight.mat.rho
weight.mat.rho %>% data.matrix() -> weight.mat.rho
rownames(weight.mat.rho) <- weight.mat.rho[,1]
weight.mat.rho <- weight.mat.rho[, 2:ncol(weight.mat.rho)]

#write.csv(weight.mat.rho, file=paste0(Save_Path, "/rho_weight.csv"))
#gzip(paste0(Save_Path, "/rho_weight.csv"), paste0(Save_Path, "/rho_weight.csv.gz"))

## delta weight
dcast(param.dt.delta, row  ~ col, value.var = "weight") -> weight.mat.delta
weight.mat.delta %>% data.matrix() -> weight.mat.delta
rownames(weight.mat.delta) <- weight.mat.delta[,1]
weight.mat.delta <- weight.mat.delta[, 2:ncol(weight.mat.delta)]

#write.csv(weight.mat.delta, file=paste0(Save_Path, "/delta_weight.csv"))
#gzip(paste0(Save_Path, "/delta_weight.csv"), paste0(Save_Path, "/delta_weight.csv.gz"))

#1. svd on rho = U * D * V^T with rank 2
rsvd(t(weight.mat.rho), k = 2) -> svd.rho
#2. project rho + delta onto the same space
# W = (rho + delta)^T U D^{-1}
W <- (weight.mat.rho + weight.mat.delta) %*% svd.rho$u %*% diag(1/svd.rho$d)
#3. Draw edges from $V$ to $W$ to show topic "vector fields" in 2D space
df_to_plot <- data.frame(
    V1 = svd.rho$v[,1],
    V2 = svd.rho$v[,2],
    W1 = W[,1],
    W2 = W[,2],
    topic = rownames(weight.mat.rho)
)

p_topic <- ggplot(df_to_plot, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2),
                    arrow = arrow(length = unit(0.1, "cm")),
                    size = 0.25) + # Make the line segments 0.25 mm thick
        geom_text_repel(aes(label = topic), size = 3) +
        ggtitle("Topic vector fields")
p_topic
#4. Draw edges after multiplying each cell's topic proportion matrix $\theta$ (cell $\times$ topic)
topics <- fread(paste0(Save_Path, "/topics.csv"))
# Note: topic.csv is python 0-based index but weight matrix is 1-based index
paste0("topic_", as.numeric(row.names(weight.mat.rho))-1) -> topic_order
cell_order <- topics$V1
topics[,..topic_order] %>% data.matrix() -> theta
rownames(theta) <- cell_order

cell_v <- theta %*% svd.rho$v
cell_w <- theta %*% W
# load cell type annotation results
load("mmultiR_annot_pancreas_marker.Rdata")

df_to_plot_cell <- data.frame(
    V1 = cell_v[, 1],
    V2 = cell_v[, 2],
    W1 = cell_w[, 1],
    W2 = cell_w[, 2],
    cell = rownames(theta),
    cell_type = out$annotation$argmax, 
    B_cell = ifelse(out$annotation$argmax == "B_cell", "Yes", "Others"),
    T_cell = ifelse(out$annotation$argmax == "T_cell", "Yes", "Others"),
    Macrophage = ifelse(out$annotation$argmax == "Macrophage", "Yes", "Others"),
    Stellate_cell = ifelse(out$annotation$argmax == "Stellate_cell", "Yes", "Others"),
    Ductal_cell_2 = ifelse(out$annotation$argmax == "Ductal_cell_2", "Yes", "Others"),
    Fibroblast = ifelse(out$annotation$argmax == "Fibroblast", "Yes", "Others"),
    Acinar_cell = ifelse(out$annotation$argmax == "Acinar_cell", "Yes", "Others"),
    Endocrine_cell = ifelse(out$annotation$argmax == "Endocrine_cell", "Yes", "Others"),
    Endothelial_cell = ifelse(out$annotation$argmax == "Endothelial_cell", "Yes", "Others"),
    Ductal_cell_1 = ifelse(out$annotation$argmax == "Ductal_cell_1", "Yes", "Others"),
    topic = apply(t(topics[,-c("V1")]), 2, which.max)
)

df_to_plot_cell$topic_surv <- df_to_plot_cell$topic
df_to_plot_cell$topic_surv[!df_to_plot_cell$topic_surv %in% c("1", "30","32","7","4","9","16")] <- "Others"

set.seed(668)
p_surv <- ggplot(df_to_plot_cell %>% sample_frac(0.03), aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = topic_surv),
                    arrow = arrow(length = unit(0.03, "cm")),
                    size = 0.2) + 
        scale_color_manual(name = c("Survial Topics"), 
                          values = c("11" = "red", "4" = "red",
                                     "26" = "blue", "6" = "blue",
                                     "Others" = "grey"))

p_surv

.ggsave(paste0(Save_Path,"/figures/2D_vector_field_cell_surv.pdf"), plot=p_surv,
        width=18, height=9)

df_to_plot_cell_final <- df_to_plot_cell %>% group_by(B_cell) %>% sample_n(1000)
p_B_cell <- ggplot(df_to_plot_cell_final, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = B_cell),
                    arrow = arrow(length = unit(0.05, "cm")),
                    size = 0.1) +
        scale_color_manual(values = c("Others" = "grey", "Yes" = "red"))
#p_B_cell

df_to_plot_cell_final <- df_to_plot_cell %>% group_by(T_cell) %>% sample_n(1000)
p_T_cell <- ggplot(df_to_plot_cell_final, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = T_cell),
                    arrow = arrow(length = unit(0.05, "cm")),
                    size = 0.1) +
        scale_color_manual(values = c("Others" = "grey", "Yes" = "red"))
#p_T_cell

df_to_plot_cell_final <- df_to_plot_cell %>% group_by(Macrophage) %>% sample_n(1000)
p_Macrophage <- ggplot(df_to_plot_cell_final, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = Macrophage),
                    arrow = arrow(length = unit(0.05, "cm")),
                    size = 0.1) +
        scale_color_manual(values = c("Others" = "grey", "Yes" = "red"))
#p_Macrophage


df_to_plot_cell_final <- df_to_plot_cell %>% group_by(Stellate_cell) %>% sample_n(1000)
p_Stellate_cell <- ggplot(df_to_plot_cell_final, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = Stellate_cell),
                    arrow = arrow(length = unit(0.05, "cm")),
                    size = 0.1) + 
        scale_color_manual(values = c("Others" = "grey", "Yes" = "red"))
#p_Stellate_cell

df_to_plot_cell_final <- df_to_plot_cell %>% group_by(Fibroblast) %>% sample_n(1000)
p_Fibroblast <- ggplot(df_to_plot_cell_final, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = Fibroblast),
                    arrow = arrow(length = unit(0.05, "cm")),
                    size = 0.1) +
        scale_color_manual(values = c("Others" = "grey", "Yes" = "red"))
#p_Fibroblast

df_to_plot_cell_final <- df_to_plot_cell %>% group_by(Acinar_cell) %>% sample_n(1000)
p_Acinar_cell <- ggplot(df_to_plot_cell_final, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = Acinar_cell),
                    arrow = arrow(length = unit(0.05, "cm")),
                    size = 0.1) +
        scale_color_manual(values = c("Others" = "grey", "Yes" = "red"))
#p_Acinar_cell

## only has 23 too few to plot
df_to_plot_cell_final <- df_to_plot_cell %>% group_by(Endothelial_cell) %>% sample_n(23)
p_Endothelial_cell <- ggplot(df_to_plot_cell_final, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = Endothelial_cell),
                    arrow = arrow(length = unit(0.05, "cm")),
                    size = 0.1) +
        scale_color_manual(values = c("Others" = "grey", "Yes" = "red"))
#p_Endothelial_cell

df_to_plot_cell_final <- df_to_plot_cell %>% group_by(Ductal_cell_1) %>% sample_n(96)
p_Ductal_cell_1 <- ggplot(df_to_plot_cell_final, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = Ductal_cell_1),
                    arrow = arrow(length = unit(0.05, "cm")),
                    size = 0.1) +
        scale_color_manual(values = c("Others" = "grey", "Yes" = "red"))
#p_Ductal_cell_1

df_to_plot_cell_final <- df_to_plot_cell %>% group_by(Ductal_cell_2) %>% sample_n(1000)
p_Ductal_cell_2 <- ggplot(df_to_plot_cell_final, aes(x = V1, y = V2)) +
        geom_segment(aes(xend = W1, yend = W2, color = Ductal_cell_2),
                    arrow = arrow(length = unit(0.05, "cm")),
                    size = 0.1) + 
        scale_color_manual(values = c("Others" = "grey", "Yes" = "red"))
#p_Ductal_cell_2

p_cell <- (p_T_cell/p_Stellate_cell/p_B_cell/p_Acinar_cell)|(p_Macrophage/p_Ductal_cell_2/p_Fibroblast/p_Ductal_cell_1/p_Endothelial_cell)

p_cell

.ggsave(paste0(Save_Path,"/figures/2D_vector_field_topic.pdf"), plot=p_topic,
        width=18, height=9)
.ggsave(paste0(Save_Path,"/figures/2D_vector_field_cell.pdf"), plot=p_cell,
        width=18, height=9)
```
